# Generated by Django 2.2.16 on 2022-07-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220729_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, help_text='Введите текст комментария', null=True, verbose_name='Текст комментария'),
        ),
    ]
