# Generated by Django 2.2.16 on 2022-07-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220730_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default='fuck', help_text='Введите текст комментария', verbose_name='Текст комментария'),
            preserve_default=False,
        ),
    ]
