# Generated by Django 2.2.16 on 2022-08-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220731_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follow',
        ),
    ]
